services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 4344
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - main

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - main


  redis:
    build:
      context: .
      dockerfile: services/Dockerfile

    networks:
      - main


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - app


volumes:
  pg_data:
  frontend:


networks:
  main: